analytics: {}
color:
  brandColors:
    - '#B8B088'
    - '#786818'
    - '#807040'
    - '#F0D808'
    - '#E0D0A0'
  brandStrength: 0.880027
  lightness: 0.742232
  rhythmicContrast: 0.833201
  saturation: 0.795198
cta: {}
layout_spectrum: 0.610197
name: Incline Beverages
opengraph: {}
purpose: []
typography_spectrum: 0.483553
